### ISSUE TITLE
Option to Round Total Bill

### ISSUE THREAD

**Issue by Sahilwagh03** [Sahilwagh03/smart-_tipper#2]
Currently, the app rounds only the tip. Adding a feature to round the total bill (including the tip) to the nearest whole number would provide users with a convenient way to finalize payments. A toggle switch could control this functionality, offering flexibility and ease of use.

**Comment by sudarshandongre** [comment]
The feature to round the total bill (including the tip) to the nearest whole number has been implemented. A toggle switch has been added to give users control over this functionality, providing flexibility and convenience when finalizing payments.![WhatsApp Image 2024-09-20 at 18 48 09 (1)](https://github.com/user-attachments/assets/c4e58bcd-be96-4c56-93c5-080fdadf2530)
![WhatsApp Image 2024-09-20 at 18 48 23 (1)](https://github.com/user-attachments/assets/7e8a5e02-e3a6-4f31-8116-dbdb12fb425e)

**Comment by sudarshandongre** [comment]
The feature to round the total bill (including the tip) to the nearest whole number has been implemented. A toggle switch has been added to give users control over this functionality, providing flexibility and convenience when finalizing payments.
![WhatsApp Image 2024-09-20 at 18 48 23 (1)](https://github.com/user-attachments/assets/07b21f19-33b9-4642-a8ce-7652c8a37e98)
![WhatsApp Image 2024-09-20 at 18 48 09 (1)](https://github.com/user-attachments/assets/31d15b7b-693e-4a17-848a-4383c377b9c9)

**Comment by Sahilwagh03** [comment]
Great
